const detailsData = {
  items: [{
    track: {
      album: {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5Pwc4xIPtQLFEnJriah9YJ',
            },
            href: 'https://api.spotify.com/v1/artists/5Pwc4xIPtQLFEnJriah9YJ',
            id: '5Pwc4xIPtQLFEnJriah9YJ',
            name: 'OneRepublic',
            type: 'artist',
            uri: 'spotify:artist:5Pwc4xIPtQLFEnJriah9YJ',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'ET',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/04PEOM6kIEeq9lRp1asNP2',
        },
        href: 'https://api.spotify.com/v1/albums/04PEOM6kIEeq9lRp1asNP2',
        id: '04PEOM6kIEeq9lRp1asNP2',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b273ec96e006b8bdfc582610ec13',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e02ec96e006b8bdfc582610ec13',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d00004851ec96e006b8bdfc582610ec13',
            width: 64,
          },
        ],
        name: 'I Ain’t Worried (Music From The Motion Picture "Top Gun: Maverick")',
        release_date: '2022-05-13',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:04PEOM6kIEeq9lRp1asNP2',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/5Pwc4xIPtQLFEnJriah9YJ',
          },
          href: 'https://api.spotify.com/v1/artists/5Pwc4xIPtQLFEnJriah9YJ',
          id: '5Pwc4xIPtQLFEnJriah9YJ',
          name: 'OneRepublic',
          type: 'artist',
          uri: 'spotify:artist:5Pwc4xIPtQLFEnJriah9YJ',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'ET',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      disc_number: 1,
      duration_ms: 148485,
      episode: false,
      explicit: false,
      external_ids: {
        isrc: 'USUM72206227',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/4h9wh7iOZ0GGn8QVp4RAOB',
      },
      href: 'https://api.spotify.com/v1/tracks/4h9wh7iOZ0GGn8QVp4RAOB',
      id: '4h9wh7iOZ0GGn8QVp4RAOB',
      is_local: false,
      name: "I Ain't Worried",
      popularity: 90,
      preview_url: null,
      track: true,
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:4h9wh7iOZ0GGn8QVp4RAOB',
    },
  },
  ],
};

export default detailsData;
