const playlistData = {
  message: 'Relax this Saturday morning',
  playlists: {
    href: 'https://api.spotify.com/v1/browse/featured-playlists?country=US&timestamp=2023-02-11T08%3A40%3A22&offset=0&limit=20',
    items: [{
      collaborative: false,
      description: 'Relax to the sound of gentle instrumental Jazz.',
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DWVqfgj8NZEp1',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWVqfgj8NZEp1',
      id: '37i9dQZF1DWVqfgj8NZEp1',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f000000033794fb85cbf0ee5d8c77e3d5',
        width: null,
      }],
      name: 'Coffee Table Jazz',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3NTc1NjQ5NiwwMDAwMDAwMDcwMTIyNzU2ZDI3ZWVkZTJlM2JlMjI5YzAwZDQ1Nzk2',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWVqfgj8NZEp1/tracks',
        total: 138,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DWVqfgj8NZEp1',
    }, {
      collaborative: false,
      description: 'The perfect soundtrack to your morning yoga session.',
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DXdVyc8LtLi96',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DXdVyc8LtLi96',
      id: '37i9dQZF1DXdVyc8LtLi96',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f0000000309c51056e92882e97f2c3740',
        width: null,
      }],
      name: 'Sunrise Yoga',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3MzYxMzM1NSwwMDAwMDAwMDg2OTk2OGNiOTdmOTU4MmY5Y2NkMGQyMjZmNTA1NzVm',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DXdVyc8LtLi96/tracks',
        total: 235,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DXdVyc8LtLi96',
    }, {
      collaborative: false,
      description: 'Have a quiet morning with this mix of something familiar and something new.',
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DWWzVPEmatsUB',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWWzVPEmatsUB',
      id: '37i9dQZF1DWWzVPEmatsUB',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f00000003b123b1df079b4a2c91ca0792',
        width: null,
      }],
      name: 'Mellow Morning',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3NjAwNTI2MCwwMDAwMDAwMDk0NzNiZjMwYTkwOGNmZjMzOGRhY2MyZWQ2YzQwNDk4',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWWzVPEmatsUB/tracks',
        total: 70,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DWWzVPEmatsUB',
    }, {
      collaborative: false,
      description: 'The soulful tunes to ease you into your day.',
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DXaXDsfv6nvZ5',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DXaXDsfv6nvZ5',
      id: '37i9dQZF1DXaXDsfv6nvZ5',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f00000003f2de418f550899021c7cabd0',
        width: null,
      }],
      name: 'Soul Coffee',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3NjAwNTIwMCwwMDAwMDAwMDgwNjE0ZDUzNDEwODQxODRiMjM4NTAwOGY4MTQ3NmE3',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DXaXDsfv6nvZ5/tracks',
        total: 75,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DXaXDsfv6nvZ5',
    }, {
      collaborative: false,
      description: 'Feel-good <a href="spotify:genre:edm_dance">dance music</a>!',
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DWSf2RDTDayIx',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWSf2RDTDayIx',
      id: '37i9dQZF1DWSf2RDTDayIx',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f0000000325d50fa7cc51b307364050f5',
        width: null,
      }],
      name: 'Happy Beats',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3NjA0ODQwMCwwMDAwMDAwMDEyNGQxOTNjZTQyMzAyNmQ5YzRkNmVlZTUxOGM4NDdk',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWSf2RDTDayIx/tracks',
        total: 150,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DWSf2RDTDayIx',
    }, {
      collaborative: false,
      description: 'The Country Coffeehouse is open! Grab a cup and lean back to some low-key country.',
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DWYiR2Uqcon0X',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWYiR2Uqcon0X',
      id: '37i9dQZF1DWYiR2Uqcon0X',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f00000003a71a8f25bac49b82f4ff9735',
        width: null,
      }],
      name: 'Country Coffeehouse',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3NTQ1MTA0NiwwMDAwMDAwMDAwNWNlMzFlMmY3MTNmN2NkNGU2MjQ5NjJmZTQ0NmUy',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWYiR2Uqcon0X/tracks',
        total: 75,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DWYiR2Uqcon0X',
    }, {
      collaborative: false,
      description: 'Relaxing piano to help you find calm and stillness within. ',
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DX1s9knjP51Oa',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DX1s9knjP51Oa',
      id: '37i9dQZF1DX1s9knjP51Oa',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f000000037c101bfeef81330ba29dc144',
        width: null,
      }],
      name: 'Calm Vibes',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3NTY4MzQxOSwwMDAwMDAwMGU4N2E3ZjgxYjRmZGNjZDU0ZjIzZDI4ZTg0MWQyODNj',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DX1s9knjP51Oa/tracks',
        total: 322,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DX1s9knjP51Oa',
    }, {
      collaborative: false,
      description: 'Curl up in your favorite spot with some sweet, mellow tunes...',
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DX6ziVCJnEm59',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DX6ziVCJnEm59',
      id: '37i9dQZF1DX6ziVCJnEm59',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f000000031c09d0e729f9c9ad8bff6739',
        width: null,
      }],
      name: 'Your Favorite Coffeehouse',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3MjkzNzQwMSwwMDAwMDAwMDNiODBjZTc4NDkwZDVkY2M4ODc0ODQ1OTc3ZDA2NWEx',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DX6ziVCJnEm59/tracks',
        total: 135,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DX6ziVCJnEm59',
    }, {
      collaborative: false,
      description: "Songs so beautiful, they'll stop you in your tracks",
      external_urls: {
        spotify: 'https://open.spotify.com/playlist/37i9dQZF1DX9Z3vMB2b8im',
      },
      href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DX9Z3vMB2b8im',
      id: '37i9dQZF1DX9Z3vMB2b8im',
      images: [{
        height: null,
        url: 'https://i.scdn.co/image/ab67706f000000034806ff1e2a4bbca552bace61',
        width: null,
      }],
      name: 'The Most Beautiful Songs in the World',
      owner: {
        display_name: 'Spotify',
        external_urls: {
          spotify: 'https://open.spotify.com/user/spotify',
        },
        href: 'https://api.spotify.com/v1/users/spotify',
        id: 'spotify',
        type: 'user',
        uri: 'spotify:user:spotify',
      },
      primary_color: null,
      public: null,
      snapshot_id: 'MTY3MzAyMjUyMCwwMDAwMDAwMDUxMjZiYjc2ODNhZmM3NWViNmNkNjBmYTYxMGYzNjNk',
      tracks: {
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DX9Z3vMB2b8im/tracks',
        total: 80,
      },
      type: 'playlist',
      uri: 'spotify:playlist:37i9dQZF1DX9Z3vMB2b8im',
    }],
    limit: 20,
    next: null,
    offset: 0,
    previous: null,
    total: 9,
  },
};

export default playlistData;
